version: '3'
services:
  todofrontend:
    build: todo-app/frontend/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
  todobackend:
    build: todo-app/backend/
    restart: always
    ports:
      - 3001:3001
  todotests:
    build: todo-app/tests/
    restart: always
    depends_on:
      - frontend
      - backend
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
